# Generated by Django 3.2 on 2021-05-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorbooking',
            name='booking_time',
            field=models.DateTimeField(),
        ),
    ]
