# Generated by Django 3.2 on 2021-05-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0002_alter_advisorbooking_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorbooking',
            name='booking_time',
            field=models.DateField(),
        ),
    ]
