# Generated by Django 3.2 on 2021-05-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0004_remove_advisorbooking_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorbooking',
            name='booking_time',
            field=models.DateTimeField(default=None),
        ),
    ]
