# Generated by Django 3.2 on 2021-05-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0005_advisorbooking_booking_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvisorBooking',
        ),
    ]
