# Generated by Django 3.2 on 2021-05-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0007_advisorbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisorbooking',
            name='advisor',
        ),
    ]
