# Generated by Django 3.2 on 2021-05-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0008_remove_advisorbooking_advisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisorbooking',
            name='user',
        ),
    ]
