# Generated by Django 3.2 on 2021-05-08 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('advisorapp', '0015_alter_advisorbooking_advisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorbooking',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advisorapp.advisor'),
        ),
        migrations.AlterField(
            model_name='advisorbooking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
