# Generated by Django 3.2 on 2021-05-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0018_auto_20210510_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorbooking',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
