# Generated by Django 3.2 on 2021-05-09 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0019_alter_advisorbooking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorbooking',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advisorapp.advisor'),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='advisorbooking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
