# Generated by Django 3.2 on 2021-05-10 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0020_auto_20210510_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisorbooking',
            name='user',
        ),
        migrations.AlterField(
            model_name='advisorbooking',
            name='advisor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookedadvisor', to='advisorapp.advisor'),
        ),
    ]
