# Generated by Django 3.2 on 2021-05-10 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0021_auto_20210510_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorbooking',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookedadvisor', to='advisorapp.advisor'),
        ),
    ]
