# Generated by Django 3.2 on 2021-05-12 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('advisorapp', '0023_auto_20210512_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='user.user'),
        ),
    ]
