# Generated by Django 3.2 on 2021-05-12 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0024_alter_advisor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='user',
        ),
        migrations.AlterField(
            model_name='advisorbooking',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advisorapp.advisor'),
        ),
    ]
