# Generated by Django 3.2 on 2021-05-13 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0025_auto_20210512_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisorbooking',
            name='advisor',
        ),
        migrations.AddField(
            model_name='advisorbooking',
            name='advise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='adviser', to='advisorapp.advisor'),
        ),
    ]
