# Generated by Django 3.2 on 2021-05-13 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('advisorapp', '0026_auto_20210513_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisorbooking',
            name='advise',
        ),
        migrations.AddField(
            model_name='advisor',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='advisorbooking',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advisorapp.advisor'),
        ),
    ]
