# Generated by Django 3.2 on 2021-05-15 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('advisorapp', '0029_auto_20210515_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorbooking',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='advisorapp.advisor'),
        ),
        migrations.AlterField(
            model_name='advisorbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='user.user'),
        ),
    ]
