# Generated by Django 3.2 on 2021-05-15 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('advisorapp', '0032_auto_20210515_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
