# Generated by Django 3.2 on 2021-05-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0033_alter_advisorbooking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisorbooking',
            name='user',
        ),
    ]
