# Generated by Django 3.2 on 2021-05-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0034_remove_advisorbooking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisorbooking',
            name='advisor',
        ),
    ]
