# Generated by Django 3.2 on 2021-05-15 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0035_remove_advisorbooking_advisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorbooking',
            name='advisor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='advisorapp.advisor'),
        ),
    ]
