# Generated by Django 3.2 on 2021-05-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0037_alter_advisorbooking_advisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorbooking',
            name='booking_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
