# Generated by Django 3.2 on 2021-05-15 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0038_alter_advisorbooking_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorbooking',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advisorapp.advisor'),
        ),
    ]
