# Generated by Django 3.2 on 2021-05-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisorapp', '0039_alter_advisorbooking_advisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorbooking',
            name='booking_time',
            field=models.DateTimeField(),
        ),
    ]
